# Generated by Django 5.2.7 on 2025-10-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_fee_amount',
            field=models.PositiveIntegerField(default=0, help_text='Extra fee (in Naira) for sizes above the threshold'),
        ),
        migrations.AddField(
            model_name='product',
            name='extra_fee_threshold',
            field=models.PositiveSmallIntegerField(default=45, help_text='Sizes above this value attract an extra fee'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_size',
            field=models.PositiveSmallIntegerField(default=45, help_text='Maximum available shoe size'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_size',
            field=models.PositiveSmallIntegerField(default=38, help_text='Minimum available shoe size'),
        ),
    ]
