# Generated by Django 5.2.7 on 2025-10-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.PositiveIntegerField(default=40),
        ),
    ]
